version: '3'
services:
  server:
    build: .
    container_name: server_web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
    - ${app_server_path}:${app_path_container}
    ports:
    - 8080:80
    working_dir: ${app_path_container}
    networks:
      - net
  client:
    build: .
    container_name: client_web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
    - ${app_client_path}:${app_path_container}
    ports:
    - 8888:80
    working_dir: ${app_path_container}
    networks:
      - net
  database:
    image: mariadb
    container_name: database
    restart: always
    environment:
      MYSQL_USER: ${db_user}
      MYSQL_ROOT_PASSWORD: ${db_password}
    ports:
    - 3306:3306
    volumes:
    - ${db_path}:/var/lib/mysql
    networks:
      - net
networks:
  net:
    driver: bridge